### ISSUE TITLE
Error: No JSON object could be decoded

### ISSUE THREAD

**Issue by vkingw** [liszd/whyliam.workflows.youdao#24]
Alfred version : 3.1.1[737]
OS : macOS 10.12.1

this my debug log, Please help to solve, thank you！

Starting debug for 'Youdao'

[2016-10-27 09:40:44][ERROR: input.scriptfilter] Code 1: 09:40:44 workflow.py:2156 DEBUG    Workflow version : 1.2.4
09:40:44 workflow.py:1568 DEBUG    Reading settings from `/Users/vincent/Library/Application Support/Alfred 3/Workflow Data/whyliam.workflows.youdao/settings.json` ...
09:40:44 workflow.py:2174 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 2164, in run
    self.check_update()
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 2409, in check_update
    if not force and not self.settings.get('**workflow_autoupdate', True):
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 1570, in settings
    self._default_settings)
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 978, in __init**
    self._load()
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 989, in _load
    for key, value in json.load(file_obj, encoding='utf-8').items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    *_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 351, in loads
    return cls(encoding=encoding, *_kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
09:40:44 workflow.py:2194 DEBUG    Workflow finished in 0.005 seconds.
[2016-10-27 09:40:45][ERROR: input.scriptfilter] Code 1: 09:40:45 workflow.py:2156 DEBUG    Workflow version : 1.2.4
09:40:45 workflow.py:1568 DEBUG    Reading settings from `/Users/vincent/Library/Application Support/Alfred 3/Workflow Data/whyliam.workflows.youdao/settings.json` ...
09:40:45 workflow.py:2174 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 2164, in run
    self.check_update()
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 2409, in check_update
    if not force and not self.settings.get('__workflow_autoupdate', True):
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 1570, in settings
    self._default_settings)
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 978, in __init__
    self._load()
  File "/Users/vincent/OneDrive/Backup/Alfred.alfredpreferences/workflows/user.workflow.1C3925FB-34A3-4901-98C7-200434A10A4B/workflow/workflow.py", line 989, in _load
    for key, value in json.load(file_obj, encoding='utf-8').items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    *_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 351, in loads
    return cls(encoding=encoding, *_kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
09:40:45 workflow.py:2194 DEBUG    Workflow finished in 0.004 seconds.

**Comment by liszd** [comment]
please delete the files
`/Users/vincent/Library/Application Support/Alfred 3/Workflow Data/whyliam.workflows.youdao`
