### ISSUE TITLE
你好，有道翻译2.1.1和2.1.0都不好使了，Alfred v3.3.2

### ISSUE THREAD

**Issue by WizardPro** [liszd/whyliam.workflows.youdao#50]
<img width="583" alt="bug" src="https://user-images.githubusercontent.com/11487593/30625456-f998cb7a-9df5-11e7-8fd1-1cb2430a280f.png">

**Comment by liszd** [comment]
请给我看看debug模式下的报错
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fjr5vhh34vj31kw0z1qb8.jpg)

**Comment by WizardPro** [comment]
以下是debug信息：

[2017-09-21 15:55:57][ERROR: input.scriptfilter] Code 1: 15:55:57 workflow.py:2404 DEBUG    update_data : None
15:55:57 workflow.py:2189 DEBUG    Workflow version : 1.2.5
15:55:57 workflow.py:1596 DEBUG    Reading settings from `/Users/xxx/Library/Application Support/Alfred 3/Workflow Data/whyliam.workflows.youdao/settings.json` ...
15:55:57 workflow.py:2207 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.257D46B1-CB68-4291-A670-DB1651DA2714/workflow/workflow.py", line 2197, in run
    self.check_update()
  File "/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.257D46B1-CB68-4291-A670-DB1651DA2714/workflow/workflow.py", line 2445, in check_update
    if not force and not self.settings.get('__workflow_autoupdate', True):
  File "/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.257D46B1-CB68-4291-A670-DB1651DA2714/workflow/workflow.py", line 1598, in settings
    self._default_settings)
  File "/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.257D46B1-CB68-4291-A670-DB1651DA2714/workflow/workflow.py", line 973, in __init__
    self._load()
  File "/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.257D46B1-CB68-4291-A670-DB1651DA2714/workflow/workflow.py", line 984, in _load
    for key, value in json.load(file_obj, encoding='utf-8').items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
15:55:57 workflow.py:2231 DEBUG    Workflow finished in 0.003 seconds.

**Comment by liszd** [comment]
前参见这个 https://github.com/liszd/whyliam.workflows.youdao/issues/24

如果出现`No JSON object could be decoded`

请删除该文件
`/Users/xxx/Library/Application\ Support/Alfred\ 3/Workflow\ Data/whyliam.workflows.youdao`

**Comment by WizardPro** [comment]
可以了，感谢！
