### ISSUE TITLE
同步到单词本报503,请问是网易同步服务的问题吗?

### ISSUE THREAD

**Issue by kevin-lucifer** [liszd/whyliam.workflows.youdao#63]
10:56:09 workflow.py:2055 DEBUG    ---------- Youdao (2.2.0) ----------
10:56:09 workflow.py:2074 ERROR    HTTP Error 503: Service Unavailable
Traceback (most recent call last):
  File "/xxxxxx/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.328FE708-5DB7-48E4-9DC5-D458497F7D6F/workflow/workflow.py", line 2067, in run
    func(self)
  File "saveword.py", line 117, in save
    if self.syncToYoudao() or (self.loginToYoudao() and self.syncToYoudao()):
  File "saveword.py", line 53, in loginToYoudao
    first_page = self.opener.open('http://account.youdao.com/login?back_url=http://dict.youdao.com&service=dict')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
10:56:09 workflow.py:2097 DEBUG    ---------- finished in 0.203s ----------

**Comment by MuYunyun** [comment]
https://github.com/liszd/whyliam.workflows.youdao/issues/60

**Comment by kevin-lucifer** [comment]
it seems they are not the same issue, actually I use my full 163 mail address as my login account ,and I'm sure my pwd is correct ,and I still get the 503 error. Could anyone test this feature again for me ? I'm really confused about this 503..., btw should I use "" to surround my vars?

**Comment by kevin-lucifer** [comment]
我大概知道原因了,
first_page = self.opener.open('http://account.youdao.com/login?back_url=http://dict.youdao.com&service=dict')
这是个非https连接,又带了用户密码,大部分企业网关会拦截掉.这个希望有时间改一下,是个比较大的安全隐患,密码在网上明文裸奔了.

**Comment by liszd** [comment]
@kevin-lucifer 有道单词本不支持https，暂时就将登入这块替换成了https。
