### ISSUE TITLE
发现一个crash错误

### ISSUE THREAD

**Issue by ifyour** [liszd/whyliam.workflows.youdao#7]
删除这个workflow 再重装还是出错，重启了Alfred也无效。

错误提示：
no json object could be decoded

debug：
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 21:23:27 workflow.py:1972 DEBUG    Workflow version : 1.2.1
21:23:27 workflow.py:1387 DEBUG    Reading settings from `/Users/MYUSERNAME/Library/Application Support/Alfred 2/Workflow Data/com.whyliam.workflows.youdao/settings.json` ...
21:23:27 workflow.py:1990 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/MYUSERNAME/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.249D703A-80E4-4F44-91AC-A25CCEBAEB8F/workflow/workflow.py", line 1980, in run
    self.check_update()
  File "/Users/MYUSERNAME/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.249D703A-80E4-4F44-91AC-A25CCEBAEB8F/workflow/workflow.py", line 2207, in check_update
    if not force and not self.settings.get('__workflow_autoupdate', True):
  File "/Users/MYUSERNAME/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.249D703A-80E4-4F44-91AC-A25CCEBAEB8F/workflow/workflow.py", line 1389, in settings
    self._default_settings)
  File "/Users/MYUSERNAME/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.249D703A-80E4-4F44-91AC-A25CCEBAEB8F/workflow/workflow.py", line 814, in __init__
    self._load()
  File "/Users/MYUSERNAME/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.249D703A-80E4-4F44-91AC-A25CCEBAEB8F/workflow/workflow.py", line 825, in _load
    for key, value in json.load(file_obj, encoding='utf-8').items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
21:23:27 workflow.py:2008 DEBUG    Workflow finished in 0.002 seconds.

**Comment by liszd** [comment]
你可以删除 /Users/MYUSERNAME/Library/Application Support/Alfred 2/Workflow Data/com.whyliam.workflows.youdao，然后再试一下

**Comment by ifyour** [comment]
正常了。

**Comment by luckyandyzhang** [comment]
出现过几次了，希望抽空修一修吧~ 谢谢~
